name: Integration for PRs
on:
  pull_request:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Fetch tag git metadata
        run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
      - uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
      - name: NuGet Auth
        shell: bash
        run: |
          [ ! -f ~/NuGet.config ] && echo '<?xml version="1.0" encoding="utf-8"?><configuration/>' > ~/NuGet.Config
          dotnet nuget add source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json \
            --configfile ~/NuGet.Config \
            -n GitHub-${{github.repository_owner}} \
            -u ${{github.repository_owner}} \
            -p ${{secrets.DAEMON_NUGET}} \
            --store-password-in-clear-text
      - name: Build
        run: dotnet build StirlingLabs.Utilities.Net.sln -c Release
      - name: Test
        run: dotnet test StirlingLabs.Utilities.Net.sln --no-build -c Release --logger GitHubActions
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Utilities.Net
          path: |
            artifacts/*.nupkg
          if-no-files-found: error
      - name: Report Coverage to PR
        uses: zattoo/output@v1
        with:
          sources: '.github/coverage/prefix,coverage/,.github/coverage/suffix'
          token: ${{github.token}}
